let ershoufang = {
    // bianHao: "insideHouseNumber-公司内部编号",
    communityName: { name: "小区名称" },
    xiaoquId: "communityId-小区名称",
    params_19: "houseNumberBuilding-栋/幢/弄/胡同",
    params_20: "houseNumberUnit-单元/号",
    params_21: "houseNumberRoom-门牌",
    suoZaiLouCeng: "currentFloor-楼层（当前）",
    zongLouCeng: "totalFloor-楼层（共）",
    params_427: "actualFloor-实际楼层",
    shi: "room-户型（室）",
    ting: "hall-户型（厅）",
    wei: "bathroom-户型（卫）",
    mianJi: "constructionArea-建筑面积",
    params_12: "innerBuildingArea-套内面积",
    title: "smartTitle-标题",
    chaoXiang: "bedroomOriented-主卧朝向",
    params_16: "houseTypes-房屋类型",
    zhuangXiuQingKuang: "decorationStatus-装修情况",
    params_22: "elevator-是否配有电梯",
    params_343: "heating-供暖",
    content_fangyuanxiangqing: "houseDetail-房源详情",
    jiaGe: "price-售价",

    picture_huxingtu: "floorPlan-户型图",
    picture_shineitu: "indoorGraph-室内图",
    picture_shiwaitu: "outdoorGraph-室外图",
    params_170: "pano-全景图Id",

    content_fuwujieshao: "serviceIntro-服务介绍",
    content_yezhuxintai: "ownerFeel-业主心态",
    params_14: "constructionAge-建造年代",
    params_17: "buildingTypes-建筑形式",
    params_18: "saleType-售卖类型",
    params_24: "propertyYears-产权年限",
    params_25: "uniqueHouse-是否为业主唯一住房",
    params_26: "houseYearLimit-房屋年限",
    params_28: "payInAdvance-首付",
    params_29: "commission-佣金比例≤",
    params_36: "houseTag-房源标签",
    params_41: "recordNumber-备案编号",
    params_81: "propertyTypes-产权类型",
    params_94: "panshiHouseId-磐石楼栋户室号ID",
    params_344: "regulation-勾选同意房源发布规则",
    isTemp: ""
};
