let ershoufang = {
//   insideHouseNumber: { name: "公司内部编号" },
  communityName: { name: "小区名称" },
  communityId: { name: "小区名称" },
  houseNumberBuilding: { name: "栋/幢/弄/胡同" },
  houseNumberUnit: { name: "单元/号" },
  houseNumberRoom: { name: "门牌" },
  currentFloor: { name: "层" },
  totalFloor: { name: "共X层" },
  actualFloor: { name: "实际楼层" },
  room: { name: "室" },
  hall: { name: "厅" },
  bathroom: { name: "卫" },
  constructArea: { name: "建筑面积" },
  params_12: "innerBuildingArea-套内面积",
  smartTitle: { name: "发布标题" },
  houseExposure: { name: "朝向" },
  houseType: { name: "房屋类型" },
  houseFit: { name: "装修情况" },
  lift: { name: "电梯" },
  heating: { name: "供暖情况" },
  houseDetail: { name: "房源详情" },
  price: { name: "售价" },

  floorPlan: { name: "户型图" },
  indoorGraph: { name: "室内图" },
  outdoorGraph: { name: "室外图" },
  panoId: { name: "全景图ID" },

  rentType: { name: "出租方式" },
  rentArea: { name: "出租面积" },
  panshiHouseId: { name: "磐石楼栋户室号ID" },
  rent_num: { name: "出租情况" },
  renter: { name: "承租人" },
  roomOrient: { name: "待租卧室朝向" },
  publicFacilities: { name: "公共设施" },
  relatedFacilities: { name: "房间设施" },
  total_num: { name: "X户合租" },
  roomMode: { name: "待租卧室" },
  priceMode: { name: "付款方式" },
  rentTime: { name: "最早入住时间" },
  commission: { name: "佣金" },
  visitTime: { name: "看房时间" },
  wholeHouseFeature: { name: "房屋亮点" },
  shareHouseFeature: { name: "房屋亮点" },
  feeDetail: { name: "费用明细" },
  rentDemand: { name: "出租要求" },
};
